# conda build conda-recipe -c omnia -c groakat -c mlgill
# conda install -c omnia -c stevend2 -c groakat -c mlgill cvxpy
package:
  name: cvxpy
  version: 0.4.2

build:
  number: 0
  string: py35_bmc

source:
  git_url: https://github.com/BlueMountainCapital/cvxpy
  git_rev: 0.4.2-bmc

requirements:
  build:
    - setuptools
    - six
    - toolz
    - cvxcanon >=0.0.22
    - fastcache
    - python
    - ecos >=2
    - scs >=1.1.3
    - multiprocess
    - numpy >=1.9
    - scipy >=0.15


  run:
    - python
    - ecos >=2
    - scs >=1.1.3
    - multiprocess
    - fastcache
    - six
    - toolz
    - numpy >=1.9
    - scipy >=0.15
    - cvxcanon >=0.0.22
    
test:
  # Python imports
  imports:
    - cvxpy
    - cvxpy.atoms
    - cvxpy.atoms.affine
    - cvxpy.atoms.elementwise
    - cvxpy.constraints
    - cvxpy.expressions
    - cvxpy.expressions.constants
    - cvxpy.expressions.variables
    - cvxpy.interface
    - cvxpy.interface.numpy_interface
    - cvxpy.lin_ops
    - cvxpy.problems
    - cvxpy.problems.problem_data
    - cvxpy.problems.solvers
    - cvxpy.tests
    - cvxpy.transforms
    - cvxpy.utilities
about:
  home: http://www.cvxpy.org/en/latest/
  license: https://github.com/cvxgrp/cvxpy
  summary: A Python-embedded modeling language for convex optimization.